### ISSUE TITLE
Request for datasets in the paper

### ISSUE THREAD

**Issue by Donghao-Li** [Nithin-GK/T2V-DDPM#2]
I have studied the code, but I sent  emails to the authors of the two datasets used in the paper and asked them to use it, but I waited for a long time but didn't receive any reply. Therefore, I would like to apply to you directly for the VIS-TH dataset and ARL-VTF dataset used in the paper. Thank you very much!

**Comment by Nithin-GK** [comment]
Hello,

I do not have the permissions required to share the dataset; only the authors have those. I would suggest to please get in touch with them again.
