### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by lgf821793883** [Nithin-GK/T2V-DDPM#5]
I would like to inquire about the specific format of the dataset under train

train
      vis  1.jpg   2.jpg ...
      nir   1.jpg  2.jpg ....

   Is the infrared and visible light data one-to-one correspondence？

**Comment by Nithin-GK** [comment]
Hello,

Yes,  for training, the infrared and visible light data are in one-to-one correspondence. Please rename the folders to TH for infrared and VIS for visible light data
