### ISSUE TITLE
About the pretrained ImageNet model

### ISSUE THREAD

**Issue by Yummy198913** [Nithin-GK/T2V-DDPM#6]
Hi，thanks for your excellent work！
Could you provide the model pretrained with the ImageNet mentioned in your work？
“For the diffusion model, we use the same parameters as for the ImageNet superresolution model as used in improved diffusion [17]. We initialize the model with the imageNet pretrained weights.”
I would be appreciate

**Comment by Nithin-GK** [comment]
Hello,

The model can be downloaded from this link

https://openaipublic.blob.core.windows.net/diffusion/jul-2021/64_256_upsampler.pt
